import requests
import re
import json
from fmhy_mapping import FILE_DEFAULTS, HEADER_RULES

GITHUB_RAW_BASE = "https://raw.githubusercontent.com/fmhy/edit/main/docs/"
FILES = list(FILE_DEFAULTS.keys())
OUTPUT_FILE = "js/data.js"

line_pattern = re.compile(
    r'^\s*\*\s*(?:⭐\s*)?(?:\*\*?)?\[(.*?)\]\((https?://[^\)]+)\)(?:\*\*?)?(?:\s*-\s*(.*))?'
)
header_pattern = re.compile(r'^#{1,3}\s+[►▷]?\s*(.*)')


def resolve_category(filename, header_context):
    """Given the current file and accumulated header text, find the best category match."""
    rules = HEADER_RULES.get(filename, [])
    for keyword, section, category in rules:
        if keyword.lower() in header_context.lower():
            return section, category
    return FILE_DEFAULTS[filename]


def scrape_fmhy():
    tools = []
    seen_domains = set()

    for filename in FILES:
        print(f"Fetching {filename}...")
        resp = requests.get(GITHUB_RAW_BASE + filename, timeout=15)
        if resp.status_code != 200:
            print(f"  Skipped (HTTP {resp.status_code})")
            continue

        current_header = ""

        for line in resp.text.split('\n'):
            # Track headers
            hm = header_pattern.match(line)
            if hm:
                raw = hm.group(1).strip()
                # Strip markdown link syntax from header
                raw = re.sub(r'\[([^\]]*)\]\([^\)]*\)', r'\1', raw)
                current_header = raw
                continue

            # Match tool lines
            match = line_pattern.search(line)
            if not match:
                continue

            name = match.group(1).strip()
            link = match.group(2).strip()
            desc = match.group(3).strip() if match.group(3) else ""
            desc = re.sub(r'\[([^\]]*)\]\([^\)]*\)', r'\1', desc)
            desc = re.sub(r'\*+', '', desc).strip()
            if not desc:
                desc = name

            domain = link.replace('https://', '').replace('http://', '').split('/')[0]
            if not domain or domain in seen_domains:
                continue

            seen_domains.add(domain)
            section, category = resolve_category(filename, current_header)

            tools.append({
                "section": section,
                "domain": domain,
                "url": link,
                "category": category,
                "description": desc,
                "pricing": "Free",
                "isEssential": False
            })

        print(f"  Total so far: {len(tools)}")

    print(f"\nDone. {len(tools)} tools extracted.")

    js = "/* Auto-generated by fmhy_importer.py */\n\n"
    js += "const FMHY_TOOLS = " + json.dumps(tools, indent=2) + ";\n\n"
    js += "const FMHY_DESC_ES = {};\nconst FMHY_DESC_CA = {};\n"

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js)

    print(f"Saved to {OUTPUT_FILE}")

    # Print category distribution
    from collections import Counter
    dist = Counter((t["section"], t["category"]) for t in tools)
    print("\nCategory distribution:")
    for (s, c), count in sorted(dist.items()):
        print(f"  [{s}] {c}: {count}")


if __name__ == "__main__":
    scrape_fmhy()
