# Mapping: (file, header_keyword) -> (section, category)
# The script checks if the keyword appears in the current header context

FILE_DEFAULTS = {
    "ai.md": ("FreeAI", "AI & Multi-Model"),
    "internet-tools.md": ("Internet Tools", "Network & DNS"),
    "system-tools.md": ("System Tools", "System Utilities"),
    "developer-tools.md": ("Developer Tools", "Dev Communities"),
    "image-tools.md": ("Image Tools", "Image Editors"),
    "video-tools.md": ("Video Tools", "Video Players"),
    "video.md": ("Streaming", "Movies & TV"),
    "audio.md": ("Music & Audio", "Music Streaming"),
    "file-tools.md": ("File Tools", "Download Managers"),
    "social-media-tools.md": ("Social Media", "Social Tools"),
    "text-tools.md": ("Text Tools", "Text Editors"),
    "gaming.md": ("Gaming", "Game Downloads"),
    "gaming-tools.md": ("Gaming Tools", "Game Launchers"),
    "reading.md": ("Books & Reading", "Ebooks"),
    "educational.md": ("Educational", "Learning Sites"),
    "downloading.md": ("Downloading", "Download Sites"),
    "torrenting.md": ("Torrenting", "Torrent Sites"),
    "privacy.md": ("Privacy & Security", "Privacy Tools"),
    "linux-macos.md": ("Linux & macOS", "Linux Apps"),
    "mobile.md": ("Mobile", "Android APKs"),
    "misc.md": ("Miscellaneous", "Indexes"),
    "storage.md": ("Apps", "Utilities"),
}

# keyword in header -> (section, category)
# checked in order, first match wins
HEADER_RULES = {
    "ai.md": [
        ("Official Model", "FreeAI", "Free Chat (Signup)"),
        ("Multi-Model", "FreeAI", "AI & Multi-Model"),
        ("Aggregate", "FreeAI", "AI & Multi-Model"),
        ("Open-Source", "FreeAI", "Free Chat (No Signup)"),
        ("No Sign-Up", "FreeAI", "Free Chat (No Signup)"),
        ("Image Gen", "FreeAI", "Image & Video Gen"),
        ("Video Gen", "FreeAI", "Image & Video Gen"),
        ("Music Gen", "FreeAI", "AI Terminal & Tasks"),
        ("Voice", "FreeAI", "AI Terminal & Tasks"),
        ("Audio", "FreeAI", "AI Terminal & Tasks"),
        ("Coding", "FreeAI", "AI Terminal & Tasks"),
        ("API", "FreeAI", "Free AI APIs"),
        ("Chatbot", "FreeAI", "Free Chat (Signup)"),
    ],
    "internet-tools.md": [
        ("Network", "Internet Tools", "Network & DNS"),
        ("DNS", "Internet Tools", "Network & DNS"),
        ("Browser Ext", "Internet Tools", "Browser Extensions"),
        ("Userscript", "Internet Tools", "Browser Extensions"),
        ("Browser", "Internet Tools", "Browsers"),
        ("Search", "Internet Tools", "Search Tools"),
        ("URL", "Internet Tools", "URL & Link Tools"),
        ("Bookmark", "Internet Tools", "Browser Extensions"),
        ("Tab", "Internet Tools", "Browser Extensions"),
        ("Scraping", "Internet Tools", "Web Archiving"),
        ("Archiv", "Internet Tools", "Web Archiving"),
    ],
    "system-tools.md": [
        ("Hardware", "System Tools", "Hardware & Specs"),
        ("Windows", "System Tools", "Windows"),
        ("File Manager", "System Tools", "File Managers"),
        ("Terminal", "System Tools", "Terminal"),
        ("Shell", "System Tools", "Terminal"),
        ("Clipboard", "System Tools", "System Utilities"),
        ("Automation", "System Tools", "System Utilities"),
        ("Customiz", "System Tools", "System Utilities"),
    ],
    "developer-tools.md": [
        ("Communit", "Developer Tools", "Dev Communities"),
        ("News", "Developer Tools", "Dev News"),
        ("IDE", "Developer Tools", "Code Editors"),
        ("Editor", "Developer Tools", "Code Editors"),
        ("Git", "Developer Tools", "Git Tools"),
        ("API", "Developer Tools", "API Tools"),
        ("Database", "Developer Tools", "Databases"),
        ("Static Site", "Developer Tools", "Hosting"),
        ("Hosting", "Developer Tools", "Hosting"),
        ("Deploy", "Developer Tools", "Hosting"),
        ("Learn", "Developer Tools", "Dev Communities"),
    ],
    "image-tools.md": [
        ("Editor", "Image Tools", "Image Editors"),
        ("Online", "Image Tools", "Online Image Editors"),
        ("Screenshot", "Image Tools", "Screenshot Tools"),
        ("Upscal", "Image Tools", "Image Enhancement"),
        ("Restor", "Image Tools", "Image Enhancement"),
        ("Compress", "Image Tools", "Image Compression"),
        ("Optim", "Image Tools", "Image Compression"),
        ("Background", "Image Tools", "Background Removal"),
        ("OCR", "Image Tools", "OCR Tools"),
        ("Color", "Image Tools", "Color Tools"),
        ("Palette", "Image Tools", "Color Tools"),
        ("Host", "Image Tools", "Image Hosting"),
        ("Convert", "Image Tools", "Image Editors"),
    ],
    "video-tools.md": [
        ("Player", "Video Tools", "Video Players"),
        ("Editor", "Video Tools", "Video Editors"),
        ("Download", "Video Tools", "Video Downloaders"),
        ("Convert", "Video Tools", "Video Converters"),
        ("Encod", "Video Tools", "Video Converters"),
        ("Screen Record", "Video Tools", "Screen Recording"),
        ("Webcam", "Video Tools", "Screen Recording"),
        ("Media Server", "Video Tools", "Media Servers"),
        ("Disc", "Video Tools", "Disc Ripping"),
        ("Rip", "Video Tools", "Disc Ripping"),
        ("Host", "Video Tools", "Video Hosting"),
    ],
    "video.md": [
        ("Anime", "Streaming", "Anime"),
        ("Live TV", "Streaming", "Live TV & Sports"),
        ("Sport", "Streaming", "Live TV & Sports"),
        ("Torrent", "Streaming", "Torrent Streaming"),
    ],
    "audio.md": [
        ("Stream", "Music & Audio", "Music Streaming"),
        ("Download", "Music & Audio", "Music Downloads"),
        ("Torrent", "Music & Audio", "Music Torrenting"),
        ("Podcast", "Music & Audio", "Podcasts"),
        ("Radio", "Music & Audio", "Radio"),
        ("Soundtrack", "Music & Audio", "Soundtracks"),
        ("Tool", "Music & Audio", "Audio Tools"),
    ],
    "file-tools.md": [
        ("Download Manager", "File Tools", "Download Managers"),
        ("Archiv", "File Tools", "File Archivers"),
        ("Compress", "File Tools", "File Archivers"),
        ("Convert", "File Tools", "File Conversion"),
        ("PDF", "File Tools", "PDF Tools"),
        ("Transfer", "File Tools", "File Transfer"),
        ("Host", "File Tools", "File Hosting"),
        ("Cloud", "File Tools", "Cloud Storage"),
        ("MEGA", "File Tools", "Cloud Storage"),
        ("Google Drive", "File Tools", "Cloud Storage"),
    ],
    "social-media-tools.md": [
        ("Discord", "Social Media", "Discord"),
        ("Reddit", "Social Media", "Reddit"),
        ("Telegram", "Social Media", "Telegram"),
        ("YouTube", "Social Media", "YouTube"),
        ("Twitter", "Social Media", "Twitter / X"),
        ("Twitch", "Social Media", "Twitch"),
        ("Bilibili", "Social Media", "Social Tools"),
    ],
    "text-tools.md": [
        ("Pastebin", "Text Tools", "Pastebins"),
        ("Translat", "Text Tools", "Translators"),
        ("Grammar", "Text Tools", "Grammar & Writing"),
        ("Writing", "Text Tools", "Grammar & Writing"),
        ("Note", "Text Tools", "Note-Taking"),
        ("Office", "Text Tools", "Office Suites"),
        ("Mind Map", "Text Tools", "Mind Mapping"),
        ("Markdown", "Text Tools", "Markup Tools"),
        ("LaTeX", "Text Tools", "Markup Tools"),
        ("Font", "Text Tools", "Fonts"),
        ("Spreadsheet", "Text Tools", "Office Suites"),
        ("To Do", "Text Tools", "Note-Taking"),
    ],
    "gaming.md": [
        ("Repack", "Gaming", "Game Repacks"),
        ("Emulat", "Gaming", "Emulation & ROMs"),
        ("ROM", "Gaming", "Emulation & ROMs"),
        ("Browser Game", "Gaming", "Browser Games"),
        ("Puzzle", "Gaming", "Puzzle & Tabletop"),
        ("Tabletop", "Gaming", "Puzzle & Tabletop"),
        ("Chess", "Gaming", "Puzzle & Tabletop"),
        ("Card Game", "Gaming", "Puzzle & Tabletop"),
        ("Virtual Reality", "Gaming", "VR Games"),
        ("VR", "Gaming", "VR Games"),
        ("Indie", "Gaming", "Indie & Retro"),
        ("Abandonware", "Gaming", "Indie & Retro"),
        ("Retro", "Gaming", "Indie & Retro"),
    ],
    "gaming-tools.md": [
        ("Launcher", "Gaming Tools", "Game Launchers"),
        ("Optimiz", "Gaming Tools", "Optimization"),
        ("Controller", "Gaming Tools", "Optimization"),
        ("Mod", "Gaming Tools", "Mods & Saves"),
        ("Save", "Gaming Tools", "Mods & Saves"),
        ("Map", "Gaming Tools", "Mods & Saves"),
        ("Steam", "Gaming Tools", "Steam & Epic"),
        ("Epic", "Gaming Tools", "Steam & Epic"),
        ("Multiplayer", "Gaming Tools", "Multiplayer"),
        ("Homebrew", "Gaming Tools", "Homebrew"),
        ("Switch", "Gaming Tools", "Homebrew"),
        ("Playstation", "Gaming Tools", "Homebrew"),
        ("Minecraft", "Gaming Tools", "Minecraft"),
        ("Tracking", "Gaming Tools", "Game Launchers"),
    ],
    "reading.md": [
        ("Ebook Reader", "Books & Reading", "Ebook Readers"),
        ("Ebook", "Books & Reading", "Ebooks"),
        ("Audiobook", "Books & Reading", "Audiobooks"),
        ("Comic", "Books & Reading", "Comics"),
        ("Manga", "Books & Reading", "Manga"),
        ("Textbook", "Books & Reading", "Academic"),
        ("Academic", "Books & Reading", "Academic"),
        ("STEM", "Books & Reading", "Academic"),
        ("Paper", "Books & Reading", "Academic"),
        ("Newspaper", "Books & Reading", "Newspapers & Magazines"),
        ("Magazine", "Books & Reading", "Newspapers & Magazines"),
        ("Light Novel", "Books & Reading", "Ebooks"),
    ],
    "educational.md": [
        ("Documentar", "Educational", "Documentaries"),
        ("Course", "Educational", "Courses"),
        ("Learn", "Educational", "Learning Sites"),
        ("Science", "Educational", "Science & Math"),
        ("Math", "Educational", "Science & Math"),
        ("Physics", "Educational", "Science & Math"),
        ("Chemistry", "Educational", "Science & Math"),
        ("Biology", "Educational", "Science & Math"),
        ("Engineer", "Educational", "Science & Math"),
        ("Space", "Educational", "Space"),
        ("Astro", "Educational", "Space"),
        ("History", "Educational", "History"),
        ("Skill", "Educational", "Skills & DIY"),
        ("Hobb", "Educational", "Skills & DIY"),
        ("DIY", "Educational", "Skills & DIY"),
        ("Music", "Educational", "Skills & DIY"),
        ("Art", "Educational", "Skills & DIY"),
    ],
    "downloading.md": [
        ("Director", "Downloading", "Download Directories"),
        ("Software", "Downloading", "Software Sites"),
        ("FOSS", "Downloading", "Software Sites"),
        ("Freeware", "Downloading", "Software Sites"),
        ("Usenet", "Downloading", "Usenet"),
        ("Debrid", "Downloading", "Debrid & Leeches"),
        ("Leech", "Downloading", "Debrid & Leeches"),
    ],
    "torrenting.md": [
        ("Client", "Torrenting", "Torrent Clients"),
        ("Private", "Torrenting", "Private Trackers"),
        ("Tracker", "Torrenting", "Private Trackers"),
    ],
    "privacy.md": [
        ("Adblock", "Privacy & Security", "Adblocking"),
        ("Antivirus", "Privacy & Security", "Antivirus"),
        ("Anti-Malware", "Privacy & Security", "Antivirus"),
        ("Malware", "Privacy & Security", "Antivirus"),
        ("Scanner", "Privacy & Security", "Antivirus"),
        ("Web Privacy", "Privacy & Security", "Web Privacy"),
        ("Browser Privacy", "Privacy & Security", "Web Privacy"),
        ("Password", "Privacy & Security", "Web Privacy"),
        ("Messenger", "Privacy & Security", "Web Privacy"),
        ("Email Priv", "Privacy & Security", "Web Privacy"),
        ("Fingerprint", "Privacy & Security", "Web Privacy"),
        ("VPN", "Privacy & Security", "VPN"),
        ("Proxy", "Privacy & Security", "Proxy"),
    ],
    "linux-macos.md": [
        ("Guide", "Linux & macOS", "Linux Guides"),
        ("Communit", "Linux & macOS", "Linux Guides"),
        ("Distro", "Linux & macOS", "Linux Distros"),
        ("Linux App", "Linux & macOS", "Linux Apps"),
        ("Linux Tool", "Linux & macOS", "Linux Tools"),
        ("Customiz", "Linux & macOS", "Linux Customization"),
        ("Desktop Env", "Linux & macOS", "Linux Customization"),
        ("Window Manager", "Linux & macOS", "Linux Customization"),
        ("Theme", "Linux & macOS", "Linux Customization"),
        ("Mac App", "Linux & macOS", "Mac Apps"),
        ("Mac", "Linux & macOS", "Mac Apps"),
    ],
    "mobile.md": [
        ("APK", "Mobile", "Android APKs"),
        ("Modded", "Mobile", "Android APKs"),
        ("Android Device", "Mobile", "Android Device"),
        ("Android Tool", "Mobile", "Android Tools"),
        ("Android Util", "Mobile", "Android Tools"),
        ("Android Camera", "Mobile", "Android Tools"),
        ("Android Browser", "Mobile", "Android Tools"),
        ("iOS App", "Mobile", "iOS Apps"),
        ("iOS Tool", "Mobile", "iOS Tools"),
        ("iOS Jail", "Mobile", "iOS Tools"),
    ],
    "misc.md": [
        ("Index", "Miscellaneous", "Indexes"),
        ("Free Stuff", "Miscellaneous", "Free Stuff"),
        ("Free Game", "Miscellaneous", "Free Stuff"),
        ("Food", "Miscellaneous", "Food & Recipes"),
        ("Recipe", "Miscellaneous", "Food & Recipes"),
        ("Drink", "Miscellaneous", "Food & Recipes"),
        ("Map", "Miscellaneous", "Maps"),
        ("Navigat", "Miscellaneous", "Maps"),
        ("News", "Miscellaneous", "News"),
        ("Health", "Miscellaneous", "Health"),
        ("Travel", "Miscellaneous", "Maps"),
        ("Sport", "Miscellaneous", "Sports"),
    ],
    "storage.md": [],
}
